version: '3.6'

services:
  api:
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
    ports:
      - "80:80"

  parser:
    build:
      dockerfile: .docker/parser/Dockerfile
      context: ./
    links:
      - api
    volumes:
      - "./htdocs:/app"